// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RigMD.Infrastructure.Persistence;

#nullable disable

namespace RigMD.Infrastructure.Migrations
{
    [DbContext(typeof(RigMdDbContext))]
    partial class RigMdDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("RigMD.Domain.Entities.ActionAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreconditionState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RemediationRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RemediationRunId");

                    b.ToTable("ActionAttempts");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.DiagnosticOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiExplanation")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfidenceLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosedCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiagnosticSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningFactors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningSigns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticSessionId")
                        .IsUnique();

                    b.ToTable("DiagnosticOutputs");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.DiagnosticSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SystemProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SystemProfileId");

                    b.ToTable("DiagnosticSessions");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.PivotEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromActionCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RemediationRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToActionCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RemediationRunId");

                    b.ToTable("PivotEvents");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.RemediationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiagnosticOutputId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticOutputId")
                        .IsUnique();

                    b.ToTable("RemediationRuns");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.RollbackEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActionAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RemediationRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RestoredState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActionAttemptId");

                    b.HasIndex("RemediationRunId");

                    b.ToTable("RollbackEvents");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.SessionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswerValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiagnosticSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticSessionId");

                    b.ToTable("SessionAnswers");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.SystemProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChipsetDriver")
                        .HasColumnType("TEXT");

                    b.Property<string>("CpuModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GpuDriver")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RamCapacity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageCapacity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemAge")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemProfiles");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.VerificationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActionAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObservedState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionAttemptId")
                        .IsUnique();

                    b.ToTable("VerificationResults");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.WarningSign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultThreshold")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WarningSigns");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.ActionAttempt", b =>
                {
                    b.HasOne("RigMD.Domain.Entities.RemediationRun", "Run")
                        .WithMany("ActionAttempts")
                        .HasForeignKey("RemediationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.DiagnosticOutput", b =>
                {
                    b.HasOne("RigMD.Domain.Entities.DiagnosticSession", "Session")
                        .WithOne("Output")
                        .HasForeignKey("RigMD.Domain.Entities.DiagnosticOutput", "DiagnosticSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.DiagnosticSession", b =>
                {
                    b.HasOne("RigMD.Domain.Entities.SystemProfile", "Profile")
                        .WithMany("Sessions")
                        .HasForeignKey("SystemProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.PivotEvent", b =>
                {
                    b.HasOne("RigMD.Domain.Entities.RemediationRun", "Run")
                        .WithMany("PivotEvents")
                        .HasForeignKey("RemediationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.RemediationRun", b =>
                {
                    b.HasOne("RigMD.Domain.Entities.DiagnosticOutput", "Output")
                        .WithOne("RemediationRun")
                        .HasForeignKey("RigMD.Domain.Entities.RemediationRun", "DiagnosticOutputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Output");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.RollbackEvent", b =>
                {
                    b.HasOne("RigMD.Domain.Entities.ActionAttempt", "AttemptTarget")
                        .WithMany()
                        .HasForeignKey("ActionAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RigMD.Domain.Entities.RemediationRun", "Run")
                        .WithMany("RollbackEvents")
                        .HasForeignKey("RemediationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttemptTarget");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.SessionAnswer", b =>
                {
                    b.HasOne("RigMD.Domain.Entities.DiagnosticSession", "Session")
                        .WithMany("Answers")
                        .HasForeignKey("DiagnosticSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.VerificationResult", b =>
                {
                    b.HasOne("RigMD.Domain.Entities.ActionAttempt", "Attempt")
                        .WithOne("Verification")
                        .HasForeignKey("RigMD.Domain.Entities.VerificationResult", "ActionAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.ActionAttempt", b =>
                {
                    b.Navigation("Verification");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.DiagnosticOutput", b =>
                {
                    b.Navigation("RemediationRun");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.DiagnosticSession", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Output");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.RemediationRun", b =>
                {
                    b.Navigation("ActionAttempts");

                    b.Navigation("PivotEvents");

                    b.Navigation("RollbackEvents");
                });

            modelBuilder.Entity("RigMD.Domain.Entities.SystemProfile", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
